services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  JTL\Nachricht\:
    resource: './src/*'

  JTL\Nachricht\Emitter\:
    resource: './src/Emitter/*'
    public: true

  JTL\Nachricht\Listener\:
    resource: './src/Listener/*'
    public: true