services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  ### General

  JTL\Nachricht\:
    resource: '../../src/*'

  JTL\Nachricht\Transport\Amqp\AmqpTransport:
    public: true
    factory: 'JTL\Nachricht\Transport\Amqp\AmqpTransportFactory:createTransport'
    arguments:
      - host: 'localhost'
        port: '5672'
        user: 'guest'
        password: 'guest'
      - '@JTL\Nachricht\Contract\Serializer\EventSerializer'

  JTL\Nachricht\Transport\Amqp\AmqpConsumer:
    public: true

  JTL\Nachricht\Emitter\:
    resource: '../../src/Emitter/*'
    public: true

  ### Examples

  JTL\Nachricht\Examples\DirectEmit\Listener\:
    resource: '../DirectEmit/Listener/*'
    public: true

  JTL\Nachricht\Examples\Amqp\Listener\:
    resource: '../Amqp/Listener/*'
    public: true