services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  ### General

  JTL\Nachricht\:
    resource: '../../src/*'

  Psr\Log\LoggerInterface: '@Monolog\Logger'

  Monolog\Logger:
    arguments:
      - 'example'

  JTL\Nachricht\TestListener:
    public: true

  JTL\Nachricht\Transport\Amqp\AmqpTransport:
    public: true
    factory: 'JTL\Nachricht\Transport\Amqp\AmqpTransportFactory:createTransport'
    arguments:
      - host: 'localhost'
        port: '5672'
        user: 'guest'
        password: 'guest'
      - '@JTL\Nachricht\Contract\Serializer\EventSerializer'
      - '@JTL\Nachricht\Listener\ListenerProvider'
      - '@Psr\Log\LoggerInterface'

  JTL\Nachricht\Event\Cache\EventCache:
    factory: 'JTL\Nachricht\Event\Cache\EventCacheCreator:create'
    arguments:
      $cacheFile: !php/const CACHE_PATH
      $lookupPathList:
        - !php/const PROJECT_ROOT_AMQP
        - !php/const PROJECT_ROOT_DIRECT
      $isDevelopment: true

  JTL\Nachricht\Transport\Amqp\AmqpConsumer:
    public: true

  JTL\Nachricht\Emitter\:
    resource: '../../src/Emitter/*'
    public: true

  ### Examples

  JTL\Nachricht\Examples\DirectEmit\Listener\:
    resource: '../DirectEmit/Listener/*'
    public: true

  JTL\Nachricht\Examples\Amqp\Listener\:
    resource: '../Amqp/Listener/*'
    public: true
