services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  JTL\Nachricht\:
    resource: '../../src/*'

  JTL\Nachricht\Queue\Client\RabbitMqClient:
    public: true

  JTL\Nachricht\Queue\Poller\RabbitMqPoller:
    public: true

  JTL\Nachricht\Emitter\:
    resource: '../../src/Emitter/*'
    public: true

  JTL\Nachricht\Examples\RabbitMq\Listener\:
    resource: './Listener/*'
    public: true