services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  JTL\Nachricht\:
    resource: '../../src/*'

  JTL\Nachricht\Emitter\:
    resource: '../../src/Emitter/*'
    public: true

  JTL\Nachricht\Examples\DirectEmit\Listener\:
    resource: './Listener/*'
    public: true