name: Testing

on: [push]

jobs:

  static-analysis:

    runs-on: ubuntu-20.04

    steps:
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'

      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: composer install --no-progress

      - name: Check Code Style
        run: composer phpstan

  check-code-style:

    runs-on: ubuntu-20.04

    steps:
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'

      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: composer install --no-progress

      - name: Check Code Style
        run: composer phpcs-dry

  testing-php81:

    runs-on: ubuntu-20.04

    strategy:
      fail-fast: false
      matrix:
        php-version:
          - "8.1"
          - "8.2"

    steps:
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "${{ matrix.php-version }}"

      - uses: actions/checkout@v2

      - name: Install dependencies
        run: composer install --no-progress

      - name: Run test suite
        run: vendor/bin/phpunit
